#!/bin/bash
cat << 'INNER_EOF' > lib/constants.ts
import { Project, Skill, TimelineEntry, Stat } from '@/types'

export const PROJECTS: Project[] = [
  {
    id         : 'pni',
    title      : 'PANCAINDO',
    subtitle   : 'B2B Wine & Spirits Platform',
    category   : 'FULL STACK',
    role       : 'Intern - Full Stack Developer',
    year       : '2024 — 2025',
    description: 'Production ecosystem for Indonesia\'s leading wine and spirits distributor. Public portal and internal CMS with RBAC and analytics.',
    status     : 'PRODUCTION',
    visibility : 'PRIVATE',
    system     : ['Public Portal', 'Internal CMS', 'RBAC', 'Analytics'],
    whatWasBuilt: ['Public commerce portal', 'Internal CMS', 'Role-based access control', 'Analytics dashboard', 'Production deployment'],
    stack      : ['Next.js', 'React', 'TypeScript', 'Tailwind', 'Cloudflare D1', 'Resend'],
    goal       : 'Build a modern and scalable platform to streamline operations, improve distribution efficiency, and support business growth in the beverage industry.',
    image      : '/projects/pni-portal.webp',
    featured   : true,
    live       : 'https://pancaindo.com',
    github     : null,
  },
  {
    id         : 'serenity',
    title      : 'SERENITY',
    subtitle   : 'Mental Health Consultation Platform',
    category   : 'UI/UX',
    role       : 'UI/UX & Frontend Developer',
    year       : '2023',
    description: 'Empathy-driven mental health platform with accessible UI, Firebase authentication, and Midtrans payment integration.',
    status     : 'COMPLETED',
    visibility : 'PUBLIC',
    system     : ['Patient App', 'Consultation Flow', 'Payment Gateway'],
    whatWasBuilt: ['Accessible UI components', 'Booking system interface', 'Payment integration UI'],
    stack      : ['Figma', 'React TS', 'TailwindCSS', 'Firebase', 'Midtrans API'],
    goal       : 'Design and build an accessible, calming digital space for users seeking mental health professional help.',
    image      : '/projects/serenity.webp',
    featured   : false,
    live       : null,
    github     : 'https://github.com/Rnvz',
  },
  {
    id         : 'beema',
    title      : 'BEEMA',
    subtitle   : 'Consultation Management Portal',
    category   : 'FULL STACK',
    role       : 'UI/UX Developer',
    year       : '2024',
    description: 'Multi-role portal for Admin, Lecturer, and Student with intuitive flows designed in Figma and built in Laravel.',
    status     : 'COMPLETED',
    visibility : 'PUBLIC',
    system     : ['Admin Dashboard', 'Student Portal', 'Lecturer Portal'],
    whatWasBuilt: ['Multi-role architecture', 'Scheduling system', 'UI/UX overhaul'],
    stack      : ['Figma', 'Laravel 12', 'MySQL', 'Blade Templates', 'Vite'],
    goal       : 'Create a streamlined consultation scheduling system for academic environments.',
    image      : '/projects/beema.webp',
    featured   : false,
    live       : null,
    github     : 'https://github.com/Rnvz',
  },
  {
    id         : 'supreme-court',
    title      : 'SUPREME COURT AI',
    subtitle   : 'Judgement Classification System',
    category   : 'AI ENGINEERING',
    role       : 'AI Engineer',
    year       : '2023',
    description: 'NLP pipeline using Gaussian Naive Bayes to classify court outcomes, deployed as an interactive Streamlit prediction app.',
    status     : 'COMPLETED',
    visibility : 'PUBLIC',
    system     : ['NLP Pipeline', 'Classification Model', 'Interactive UI'],
    whatWasBuilt: ['Data preprocessing', 'Model training & tuning', 'Streamlit web interface'],
    stack      : ['Python', 'Scikit-learn', 'Pandas', 'Optuna', 'Streamlit'],
    goal       : 'Automate the classification of legal judgement documents using natural language processing.',
    image      : '/projects/supreme-court.webp',
    featured   : false,
    live       : null,
    github     : 'https://github.com/Rnvz',
  },
  {
    id         : 'gym',
    title      : 'GYM SYSTEM',
    subtitle   : 'Freelance Full Stack',
    category   : 'FULL STACK',
    role       : 'Full Stack Developer',
    year       : '2024',
    description: 'End-to-end gym management with Figma-designed UI, React frontend, and Node.js + Prisma backend.',
    status     : 'PRODUCTION',
    visibility : 'PRIVATE',
    system     : ['Member Management', 'Billing System', 'Admin Dashboard'],
    whatWasBuilt: ['Full-stack architecture', 'Database schema', 'Responsive UI'],
    stack      : ['React TS', 'TailwindCSS', 'Node.js', 'Prisma', 'SQLite', 'Figma'],
    goal       : 'Digitize gym operations and member management for a local fitness center.',
    image      : '/projects/gym-system.webp',
    featured   : false,
    live       : null,
    github     : 'https://github.com/Rnvz',
  },
  {
    id         : 'nofake',
    title      : 'NOFAKE',
    subtitle   : 'Hoax Verification & Education',
    category   : 'UI/UX',
    role       : 'UI/UX & Frontend Developer',
    year       : '2023',
    description: 'Credibility-focused UI/UX prioritizing clear information hierarchy, with a scalable React and TailwindCSS frontend to combat digital misinformation.',
    status     : 'COMPLETED',
    visibility : 'PUBLIC',
    system     : ['Verification Portal', 'Educational Hub'],
    whatWasBuilt: ['Trust-centric UI design', 'Frontend implementation', 'Content management UI'],
    stack      : ['React', 'Tailwind', 'Firebase', 'Figma'],
    goal       : 'Design a trustworthy platform to help users identify and learn about digital misinformation.',
    image      : '/projects/pni-portal.webp',
    featured   : false,
    live       : null,
    github     : 'https://github.com/Rnvz',
  },
  {
    id         : 'peluangnusantara',
    title      : 'PELUANG NUSANTARA',
    subtitle   : 'Crowdfunding Platform',
    category   : 'EXPERIMENTS',
    role       : 'UI/UX & Frontend Developer',
    year       : '2023',
    description: 'Accessible and trust-building UI/UX for a crowdfunding platform developed with semantic HTML, CSS, and JavaScript focusing on cross-browser consistency.',
    status     : 'COMPLETED',
    visibility : 'PUBLIC',
    system     : ['Campaign Pages', 'Donation Flow'],
    whatWasBuilt: ['Semantic HTML structure', 'Custom CSS styling', 'Vanilla JS interactions'],
    stack      : ['Figma', 'HTML5', 'CSS3', 'JavaScript'],
    goal       : 'Experiment with core web technologies to build a responsive crowdfunding interface.',
    image      : '/projects/serenity.webp',
    featured   : false,
    live       : null,
    github     : 'https://github.com/Rnvz',
  },
]

export const SKILLS: Skill[] = [
  { name: 'HTML5',      icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg' },
  { name: 'CSS3',       icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg' },
  { name: 'JavaScript', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg' },
  { name: 'TypeScript', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg' },
  { name: 'Python',     icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg' },
  { name: 'C',          icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/c/c-original.svg' },
  { name: 'Next.js',    icon: 'https://cdn.simpleicons.org/nextdotjs/white' },
  { name: 'React',      icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg' },
  { name: 'Laravel',    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/laravel/laravel-original.svg' },
  { name: 'Tailwind',   icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg' },
  { name: 'Node.js',    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg' },
  { name: 'MySQL',      icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original-wordmark.svg' },
  { name: 'SQLite',     icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sqlite/sqlite-original.svg' },
  { name: 'Anaconda',   icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/anaconda/anaconda-original.svg' },
  { name: 'Matplotlib', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/matplotlib/matplotlib-original.svg' },
  { name: 'Pandas',     icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pandas/pandas-original.svg' },
  { name: 'NumPy',      icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/numpy/numpy-original.svg' },
  { name: 'Scikit-learn',icon: 'https://cdn.simpleicons.org/scikitlearn' },
  { name: 'BioPython',  icon: '/icons/biopython.svg' },
  { name: 'Linux',      icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/linux/linux-original.svg' },
  { name: 'Fedora',     icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/fedora/fedora-original.svg' },
  { name: 'Cisco',      icon: 'https://cdn.simpleicons.org/cisco/white' },
  { name: 'Git',        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg' },
  { name: 'GitHub',     icon: 'https://cdn.simpleicons.org/github/white' },
  { name: 'Jira',       icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jira/jira-original.svg' },
  { name: 'Figma',      icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg' },
  { name: 'Cloudflare', icon: 'https://cdn.simpleicons.org/cloudflare' },
  { name: 'Firebase',   icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/firebase/firebase-original.svg' },
]

export const CERTIFICATIONS = [
  {
    id: 'cert1',
    title: 'Alibaba Cloud Certified Associate - Cloud Engineer',
    issuer: 'Alibaba Cloud',
    year: '2024',
    image: '/projects/cert-alibaba.jpg',
  },
  {
    id: 'cert2',
    title: 'Learning SOLID Programming Principles',
    issuer: 'DICODING',
    year: '2023',
    image: '/projects/cert-solid.png',
  },
  {
    id: 'cert3',
    title: 'Basic AI Course',
    issuer: 'DICODING',
    year: '2023',
    image: '/projects/cert-ai.png',
  },
]

export const STATS: Stat[] = [
  { value: '3+',  label: 'Years building' },
  { value: '10+', label: 'Projects shipped' },
  { value: '2',   label: 'Production systems' },
]
INNER_EOF
